name: Pull Request

on: [pull_request]

jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (provide access)
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

  unusedexports:
    name: Find unused exports (dead code)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout (provide access)
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run ts-prune
        run: yarn ts-prune --error

  unittest:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout (provide access)
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run unit tests
        run: yarn test
